version: "3.9"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: web_security_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./Database/backup_web_security_db_2025-12-21_005532.sql:/docker-entrypoint-initdb.d/01-seed.sql:ro

  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/web_security_db?useSSL=false&allowPublicKeyRetrieval=true&sslMode=DISABLED
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456
      LABS_HOST: ${LABS_HOST:-localhost}
    volumes:
      - ./backend/backend:/app
      - maven-repo:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: ./mvnw spring-boot:run

  frontend:
    build:
      context: ./frontend/lockbyte-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8082/api}
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend/lockbyte-ui:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"

volumes:
  db-data:
  maven-repo:
